version: '3.8'

services:
  # Local development deployment without USB devices
  encryptedmeshlink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eml-station-local
    restart: unless-stopped
    
    # Environment configuration
    environment:
      - NODE_ENV=development
      - ENCRYPTEDMESHLINK_AUTO_UPDATE=false
      - EML_LOCAL_TESTING=true
    
    # Volume mounts for persistence (no A/B deployment for local)
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Network configuration
    ports:
      - "8447:8447"
      - "3000:3000"
    
    # Health check for container validation
    healthcheck:
      test: ["CMD", "npx", "tsx", "encryptedmeshlink.ts", "help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
