version: '3.8'

services:
  # Raspberry Pi optimized deployment
  encryptedmeshlink-pi:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: eml-pi-station
    restart: unless-stopped
    
    # Environment configuration for Pi
    environment:
      - NODE_ENV=production
      - ENCRYPTEDMESHLINK_AUTO_UPDATE=true
      - ENCRYPTEDMESHLINK_UPDATE_INTERVAL_HOURS=1
      - ENCRYPTEDMESHLINK_UPDATE_BRANCH=master
      - EML_LOCAL_TESTING=false
    
    # Volume mounts for persistence and A/B deployment
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.git:/app/.git:ro  # Read-only git for auto-updates
      - deployment-staging:/app/deployment/staging
      - deployment-production:/app/deployment/production
      - deployment-backup:/app/deployment/backup
    
    # Network configuration
    ports:
      - "8447:8447"
      - "3000:3000"
    
    # USB device access for Meshtastic
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    
    # Privileged access for hardware
    privileged: true
    
    # Health check optimized for Pi (longer timeouts)
    healthcheck:
      test: ["CMD", "npx", "tsx", "encryptedmeshlink.ts", "help"]
      interval: 60s
      timeout: 30s
      retries: 2
      start_period: 30s
    
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  deployment-staging:
    driver: local
  deployment-production:
    driver: local
  deployment-backup:
    driver: local
